# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'

    # 1. Сначала линтер. Если падает — стоп.
    - name: Lint
      run: golangci-lint run
  
    # 2. Быстрые юнит-тесты. 
    # Мы явно указываем пути, чтобы не трогать интеграционные тесты.
    # Или используем теги, если тесты помечены.
    - name: Run Unit Tests
      run: go test -v ./pkg/... ./internal/... 
      # ^^^ Тестируем только внутреннюю логику и пакеты, исключая папки с интеграционными тестами
  
    # 3. Сборка. Делаем бинарник только если стиль и логика в порядке.
    - name: Build
      run: go build -v ./cmd/myapp
  
    # 4. А вот тяжелые тесты мы сюда НЕ ставим.
    # Они пойдут в отдельный workflow или отдельный job, который запускается позже. 
